name: api_dictionary
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  speech_to_text: ^6.6.0
  connectivity_plus: ^5.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  lottie: ^3.1.0
  shimmer: ^3.0.0
  share_plus: ^7.2.2
  fluttertoast: ^8.2.4
  just_audio: ^0.9.36
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/icons/
   - assets/fonts/
   - assets/lotties/
   - assets/texts/

  fonts:
   - family: NotoSansDisplay
     fonts:
       - asset: assets/fonts/NotoSansDisplay-Regular.ttf
       - asset: assets/fonts/NotoSansDisplay-Italic.ttf
         style: italic